"""Add indexes

Revision ID: 06e24459645c
Revises: 3995a6e99939
Create Date: 2024-06-20 23:35:15.399075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e24459645c'
down_revision: Union[str, None] = '3995a6e99939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tour_name_type_agency_index', 'tour', ['tour_name', 'tour_type_id', 'tour_agency_id'], unique=False)
    op.create_index('tour_prices_index', 'tour_price', ['scraped_date', 'scraped_time', 'tour_approved', 'tour_price', 'tour_price_pp', 'tour_config_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tour_prices_index', table_name='tour_price')
    op.drop_index('tour_name_type_agency_index', table_name='tour')
    # ### end Alembic commands ###
