"""create uniqueConstraint

Revision ID: 2b69eec3d630
Revises: b8f0c6983f22
Create Date: 2024-12-14 18:43:23.387718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b69eec3d630'
down_revision: Union[str, None] = 'b8f0c6983f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tour_config_dates_tour', 'tour_config', ['start_tour_date', 'end_tour_date', 'tour_id', 'tour_length'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tour_config_dates_tour', 'tour_config', type_='unique')
    # ### end Alembic commands ###
