"""Create needed indexes

Revision ID: 3608b0efa796
Revises: 7d53a8f33692
Create Date: 2024-11-25 10:10:30.089433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3608b0efa796'
down_revision: Union[str, None] = '7d53a8f33692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_country', 'country', ['country_name', 'country_code'], unique=False)
    op.create_index('idx_tour_query', 'tour', ['tour_name', 'tour_type_id', 'tour_agency_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tour_query', table_name='tour')
    op.drop_index('idx_country', table_name='country')
    # ### end Alembic commands ###
