"""Add test index for tour operator

Revision ID: 3995a6e99939
Revises: 0c2d42e31022
Create Date: 2024-06-20 23:17:19.330480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3995a6e99939'
down_revision: Union[str, None] = '0c2d42e31022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name_url_index', 'tour_agency', ['agency_name', 'agency_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name_url_index', table_name='tour_agency')
    # ### end Alembic commands ###
