"""Add basic models

Revision ID: 41078e811b74
Revises: 
Create Date: 2024-02-03 15:29:28.890041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = '41078e811b74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=30), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code'),
    sa.UniqueConstraint('country_name')
    )
    op.create_table('tour_agency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_name', sa.String(length=30), nullable=False),
    sa.Column('agency_url', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_name'),
    sa.UniqueConstraint('agency_url')
    )
    op.create_table('tour_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_tour_id', sa.String(), nullable=True),
    sa.Column('omnibus_key', sa.String(), nullable=True),
    sa.Column('tour_name', sa.String(length=100), nullable=False),
    sa.Column('tour_url', sa.String(length=1000), nullable=False),
    sa.Column('tour_type_id', sa.Integer(), nullable=False),
    sa.Column('tour_agency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tour_agency_id'], ['tour_agency.id'], ),
    sa.ForeignKeyConstraint(['tour_type_id'], ['tour_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['tour.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_url')
    )
    op.create_table('tour_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_length', sa.Integer(), nullable=True),
    sa.Column('start_tour_date', sa.Date(), nullable=False),
    sa.Column('end_tour_date', sa.Date(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('start_location', sa.String(length=100), nullable=True),
    sa.Column('location_additional_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tour_id'], ['tour.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tours_countries_association',
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tour.id'], ),
    sa.PrimaryKeyConstraint('tour_id', 'country_id')
    )
    op.create_table('tour_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraped_date', sa.Date(), nullable=False),
    sa.Column('tour_approved', sa.Boolean(), nullable=False),
    sa.Column('tour_price', sa.Float(), nullable=False),
    sa.Column('tour_price_pp', sa.Float(), nullable=False),
    sa.Column('tour_config_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tour_config_id'], ['tour_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tour_price')
    op.drop_table('tours_countries_association')
    op.drop_table('tour_config')
    op.drop_table('photos')
    op.drop_table('tour')
    op.drop_table('tour_type')
    op.drop_table('tour_agency')
    op.drop_table('country')
    # ### end Alembic commands ###
