"""Add index for tour prices

Revision ID: 7d53a8f33692
Revises: 0c2d42e31022
Create Date: 2024-11-24 13:38:31.607979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d53a8f33692'
down_revision: Union[str, None] = '0c2d42e31022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_tour_price_query', 'tour_price', ['scraped_time', 'scraped_date', 'tour_config_id', 'tour_price', 'tour_price_pp', 'tour_approved'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tour_price_query', table_name='tour_price')
    # ### end Alembic commands ###
