"""Create index for tour_config

Revision ID: b8f0c6983f22
Revises: 3608b0efa796
Create Date: 2024-11-25 10:22:37.734056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f0c6983f22'
down_revision: Union[str, None] = '3608b0efa796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_tour_config_query', 'tour_config', ['start_tour_date', 'end_tour_date', 'tour_id', 'tour_length', 'start_location', 'location_additional_cost'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tour_config_query', table_name='tour_config')
    # ### end Alembic commands ###
